### ISSUE TITLE
Not able to run app on Android Samsung Galaxy A22

### ISSUE THREAD

**Issue by benndip** [ViroCommunity/expo-viro-starter-kit#1]
Here is a link to the error that shown.

[https://drive.google.com/file/d/1n2iUqTcYDON5ugndGrqQ0feGUiJ6-PPw/view?usp=sharing](url)

**Comment by jeanmarie15** [comment]
same error on a Xiaomi.

**Comment by monkeyK1n9** [comment]
Hello @jeanmarie15 and @benndip , how did you solve this issue? I am facing the same problem

**Comment by jeanmarie15** [comment]
I don't remember well because I stop the project, But I think I had to use an old version

**Comment by monkeyK1n9** [comment]
> I don't remember well because I stop the project, But I think I had to use an old version

An old version of viro-react or a downgraded android version?

**Comment by jeanmarie15** [comment]
> > I don't remember well because I stop the project, But I think I had to use an old version
> 
> An old version of viro-react or a downgraded android version?

an old version of viro-react

**Comment by benndip** [comment]
Hello @monkeyK1n9 , I didn't go through this part when building my app. What I did was, I used a bare React native project(Not expo), then I added Expo to the React Native app. I think you should do that instead since Viro and Expo are not well stable yet for many versions

**Comment by monkeyK1n9** [comment]
> Hello @monkeyK1n9 , I didn't go through this part when building my app. What I did was, I used a bare React native project(Not expo), then I added Expo to the React Native app. I think you should do that instead since Viro and Expo are not well stable yet for many versions

Okay, I will try this out, thanks. 

@jeanmarie15 , which version worked for you?

**Comment by CodeLuca** [comment]
1 year later and I'm trying to make this run, any clues that helped you @monkeyK1n9 ?
